#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

source "$(dirname $0)/../utils/functions.sh"
cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

install_npm_dependencies () {
  if command_exists "npm";
  then
    info '› installing npm dependencies'

    # TODO: future hide output and only show if error
    while IFS= read -r line
    do
      npm install $line --global --silent
    done < "$(dirname $0)/../node/npm-packages.txt"

    success '› installed npm dependencies'
  else
    fail '✗ error installing npm dependencies'
  fi
}

# run install npm dependencies (global)
install_npm_dependencies

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
